### ISSUE TITLE
bug: ~InputBufferUnderrunError

### ISSUE THREAD

**Issue by Maphan** [evex-dev/linejs#45]
I got an error InputBufferUnderrunError when running time

**Comment by EdamAme-x** [comment]
I'll fix

**Comment by EdamAme-x** [comment]
I'll fix

**Comment by komkeao** [comment]
Same issue, and sometimes, after running for a while, the 'on message' events are delayed."

**Comment by komkeao** [comment]
Do you have any updates?

**Comment by EdamAme-x** [comment]
For now, I will choose the option of ignoring the error until I can figure out the cause.

**Comment by komkeao** [comment]
> For now, I will choose the option of ignoring the error until I can figure out the cause.

How can I ignore the error?

**Comment by Suphachock** [comment]
Now this problem solved?

**Comment by EdamAme-x** [comment]
This error is accidental and has been suppressed.
Please try

**Comment by Suphachock** [comment]
Why I still got an errror?

**Comment by EdamAme-x** [comment]
You probably forgot to upgrade the version

**Comment by Suphachock** [comment]
I update version yesterday but problem not solved

**Comment by EdamAme-x** [comment]
Hmm
Wait a minutes
I will solve this after school

**Comment by mongkonkit** [comment]
Now this problem solved?

**Comment by mahanakornsmati** [comment]
Now this problem solved?

**Comment by EdamAme-x** [comment]
Wait a moment.
for now, please use auto runner (if process is failed, to retry)

**Comment by piloking** [comment]
InputBufferUnderrunError is most often caused by an incorrect response from line server.
Which code causes the error when you run it?

**Comment by fangda123** [comment]
I tested it, and this bug occurs within 2 minutes after running the project. The code stops working every time. Please fix it

**Comment by piloking** [comment]
What error stack is shown?

**Comment by fangda123** [comment]
<img width="1368" alt="Screenshot 2567-11-15 at 03 44 15" src="https://github.com/user-attachments/assets/cc9a0fd3-d451-44f0-84bb-3b44ba562c2f">

**Comment by fangda123** [comment]
<img width="1073" alt="Screenshot 2567-11-15 at 04 22 52" src="https://github.com/user-attachments/assets/d988499d-1f87-44f7-a88b-5c13159ef0ec">
<img width="591" alt="Screenshot 2567-11-15 at 04 22 29" src="https://github.com/user-attachments/assets/b461cd27-19b5-4637-b7dc-f2f0326b64ef">
<img width="1006" alt="Screenshot 2567-11-15 at 04 19 53" src="https://github.com/user-attachments/assets/7482dba1-0512-4306-a6f4-0bcbd4e4cce9">

**Comment by EdamAme-x** [comment]
Thanks, we'll check

**Comment by piloking** [comment]
![0](https://private-user-images.githubusercontent.com/75300206/386373612-7482dba1-0512-4306-a6f4-0bcbd4e4cce9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzE1MDksIm5iZiI6MTczMTc3MTIwOSwicGF0aCI6Ii83NTMwMDIwNi8zODYzNzM2MTItNzQ4MmRiYTEtMDUxMi00MzA2LWE2ZjQtMGJjYmQ0ZTRjY2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDE1MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NzA2M2QyOGJjMzYxZmU1NGRlM2Y1MDU1NDE4ZDc5YzFmYmE3ZjhhNDY5ZDJlMjhhYzhjNGVjZGQ0MmZiYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KMwFDr2WiKojTYXGJwOUDgcjR9zNR7SlFzkT7e9pj4Q)
This log shows that the server returned 0 bytes of body data.

If you are using the client.sync function, try using try/catch as the server may not return data due to its specifications.
Or, there may be a problem with the linejs's request.

**Comment by EdamAme-x** [comment]
I found the cause. I will issue a fix patch after this.

**Comment by EdamAme-x** [comment]
maybe solved by this
https://github.com/evex-dev/linejs/releases/tag/1.9.0
